/** AnalysisReport → a Markdown review comment. Pure. */
import type { AnalysisReport } from "./model.js";
import { loc } from "./model.js";

const SEV = { high: "🔴", medium: "🟠", low: "🟡" } as const;

function short(ref: string): string {
  return /^[0-9a-f]{40}$/i.test(ref) ? ref.slice(0, 7) : ref;
}

export function renderMarkdown(r: AnalysisReport): string {
  const o: string[] = [];
  const s = r.radius;

  o.push("<!-- blast-radius -->");
  o.push("## 🧨 Blast Radius");
  o.push("");
  const parts = [
    `**${s.nodes.length} node${s.nodes.length === 1 ? "" : "s"}**`,
    `${r.changedSymbols.length} changed`,
    r.findings.length ? `**${r.findings.length} scope finding${r.findings.length === 1 ? "" : "s"}**` : "0 scope findings",
    `**${r.testPlan.selected.length} test${r.testPlan.selected.length === 1 ? "" : "s"}**` +
      (r.testPlan.coverageGaps.length ? ` (${r.testPlan.coverageGaps.length} gap${r.testPlan.coverageGaps.length === 1 ? "" : "s"})` : ""),
  ];
  o.push(parts.join(" · "));
  o.push("");

  if (r.intent) {
    o.push(`> **Intent** — _${JSON.stringify(r.intent.text.slice(0, 160))}_  `);
    o.push(`> source: \`${r.intent.source}\`` + (r.range.checkpoint ? ` · \`${r.range.checkpoint}\`` : ""));
  } else {
    o.push("> **Intent** — none found. Scope drift can't be judged; showing radius + tests only.");
  }
  o.push("");

  if (r.findings.length) {
    o.push(`### ⚠️ Scope check — ${r.findings.length} change(s) look outside the ask`);
    o.push("");
    o.push("| | Changed symbol | Why | Dependents |");
    o.push("|--|--|--|--|");
    for (const f of r.findings) {
      o.push(`| ${SEV[f.severity]} | \`${f.symbol.qualifiedName}\`${loc(f.symbol) ? ` \`${loc(f.symbol)}\`` : ""} | ${f.reason} | ${f.dependentsCount} |`);
    }
    o.push("");
    o.push("<details><summary>Evidence</summary>", "");
    for (const f of r.findings) {
      o.push(`**\`${f.symbol.qualifiedName}\`**`);
      for (const e of f.evidence) o.push(`- ${e}`);
      o.push("");
    }
    o.push("</details>", "");
  } else if (r.intent) {
    o.push("### ✅ Scope check — every change maps to the stated intent", "");
  }

  const tp = r.testPlan;
  if (tp.selected.length) {
    const cover = tp.coverageGaps.length === 0 ? "covers every changed symbol" : `covers all but ${tp.coverageGaps.length}`;
    o.push(`### 🧪 Recommended tests — ${tp.selected.length}, ${cover}`, "");
    if (tp.command) o.push("```bash", tp.command, "```", "");
    o.push("<details><summary>Why these tests</summary>", "");
    o.push("| Test | Covers | Distance |", "|--|--|--|");
    for (const t of tp.selected) {
      o.push(`| \`${t.ref.name}\` | ${t.covers.map((c) => `\`${c}\``).join(", ")} | ${t.distance} |`);
    }
    if (tp.coverageGaps.length) {
      o.push("", `**No test reaches:** ${tp.coverageGaps.map((g) => `\`${g}\``).join(", ")} — verify manually.`);
    }
    o.push("", "</details>", "");
  } else {
    o.push("### 🧪 Recommended tests — none found in the blast radius", "");
  }

  const byRel: Record<string, number> = {};
  for (const n of s.nodes) byRel[n.relation] = (byRel[n.relation] ?? 0) + 1;
  o.push(
    `<details><summary>Full blast radius — ${s.nodes.length} nodes</summary>`,
    "",
    Object.entries(byRel).sort((a, b) => b[1] - a[1]).map(([k, v]) => `\`${k}\` ${v}`).join(" · "),
    "",
    "| Node | Relation | Dist | From |",
    "|--|--|--|--|",
  );
  for (const n of s.nodes.slice(0, 50)) {
    o.push(`| \`${n.ref.qualifiedName}\`${n.isTest ? " 🧪" : ""} | \`${n.relation}\` | ${n.distance} | ${n.originSymbols.map((x) => `\`${x}\``).join(", ")} |`);
  }
  o.push("", "</details>", "");

  o.push("---");
  o.push(`<sub>Generated by Blast Radius from Entire Graph · \`${short(r.range.base)}\`..\`${short(r.range.head)}\` · every row is backed by the graph path behind it</sub>`);
  return o.join("\n");
}

export function renderJson(r: AnalysisReport): string {
  return JSON.stringify(r, null, 2);
}
